In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
###Create two matrices of 512,512 size with random values between 0 and 1
A = np.random.rand(512,512)
B = np.random.rand(512,512) 


In [7]:
#Matrix multiplication
A.dot(B) 

array([[125.41545168, 122.79081664, 131.46467117, ..., 128.35192521,
        125.89920693, 127.82363634],
       [124.53356198, 122.74445388, 130.2559892 , ..., 129.65579958,
        127.8320126 , 128.50586661],
       [127.97943416, 126.4387796 , 132.99297895, ..., 135.34435213,
        130.9316517 , 129.91261002],
       ...,
       [130.47804385, 123.81168248, 132.58546797, ..., 129.66790171,
        127.72526994, 134.59799621],
       [123.69119868, 118.16148005, 123.0392518 , ..., 122.02353052,
        123.07173506, 124.75447118],
       [125.00239473, 125.16887622, 132.90414376, ..., 131.01504149,
        130.68306067, 131.20313451]])

In [8]:
##Transpose of matrix A
A.T

array([[0.43119907, 0.05498074, 0.02079397, ..., 0.42857294, 0.49354219,
        0.24200535],
       [0.44331335, 0.02407967, 0.62375032, ..., 0.48621261, 0.17148868,
        0.07154394],
       [0.72933819, 0.51812923, 0.92864832, ..., 0.4627331 , 0.68490088,
        0.1709774 ],
       ...,
       [0.49018503, 0.11398863, 0.93481833, ..., 0.11427102, 0.79236174,
        0.91243368],
       [0.19932124, 0.94587884, 0.11039129, ..., 0.65594759, 0.07361826,
        0.20437254],
       [0.56396165, 0.44670033, 0.87099515, ..., 0.88547802, 0.05249539,
        0.01444346]])

In [9]:
##Inverse of matrix A 
np.linalg.inv(A)

array([[-0.06548271,  0.16060886,  0.01949596, ...,  0.08070369,
        -0.12767307,  0.06963621],
       [ 1.44928498,  0.28865837, -1.88254815, ...,  0.78178325,
         0.63561005, -0.23428793],
       [-0.04282392, -0.21611634,  0.12562577, ...,  0.08049493,
         0.17841155, -0.0181947 ],
       ...,
       [-0.94386573, -0.26583576,  1.22760067, ..., -0.1756753 ,
        -0.1135994 ,  0.22737809],
       [ 0.91879373,  0.10823583, -1.04398685, ...,  0.540431  ,
         0.40871268, -0.3402777 ],
       [-0.62096307, -0.52493525,  1.57107699, ..., -0.26502589,
        -0.61328038, -0.06755592]])